Update ttest.yml

diff --git a/.github/workflows/ttest.yml b/.github/workflows/ttest.yml
--- a/.github/workflows/ttest.yml
+++ b/.github/workflows/ttest.yml
@@ -16,7 +16,7 @@ jobs:
       matrix:
         api-level: [30]
         target: ["google_apis"]
-        arch: ["arm64-v8a"]
+        arch: ["x86_64"]
 
     steps:
       - name: Check out code
@@ -39,8 +39,10 @@ jobs:
       - name: Accept Android SDK licenses
         run: yes | $HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
 
-      - name: Install Emulator
-        run: $HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager "emulator" "platform-tools" "system-images;android-30;google_apis;arm64-v8a"
+      - name: Install Emulator and Dependencies
+        run: |
+          sdkmanager --update
+          sdkmanager --install "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
 
       - name: Start Android Emulator
         uses: reactivecircus/android-emulator-runner@v2
@@ -49,26 +51,24 @@ jobs:
           target: ${{ matrix.target }}
           arch: ${{ matrix.arch }}
           profile: pixel_3a
-          emulator-options: "-no-snapshot -no-boot-anim"
+          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -accel off"
           force-avd-creation: true
           emulator-boot-timeout: 600
-          disable-animations: true
-          script: |
-            adb wait-for-device
-            boot_completed=false
-            for i in {1..30}; do
-              if adb -s emulator-5554 shell getprop sys.boot_completed | grep -q "1"; then
-                boot_completed=true
-                break
-              fi
-              sleep 10
-            done
-            if [ "$boot_completed" = false ]; then
-              echo "Emulator failed to boot."
-              exit 1
+
+      - name: Wait for Emulator Boot
+        run: |
+          boot_completed=false
+          for i in {1..30}; do
+            if adb -s emulator-5554 shell getprop sys.boot_completed | grep -q "1"; then
+              boot_completed=true
+              break
             fi
-            adb devices
-            adb shell input keyevent 82
+            sleep 10
+          done
+          if [ "$boot_completed" = false ]; then
+            echo "Emulator failed to boot."
+            exit 1
+          fi
 
       - name: Run Tests
         run: ./gradlew connectedAndroidTest --max-workers=2 --continue --no-daemon --info
