Update ttest.yml

diff --git a/.github/workflows/ttest.yml b/.github/workflows/ttest.yml
--- a/.github/workflows/ttest.yml
+++ b/.github/workflows/ttest.yml
@@ -40,14 +40,14 @@ jobs:
           export ANDROID_HOME=$HOME/Library/Android/sdk
           export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
 
-          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --no_https
-          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --no_https
+          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
+          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update || true
           $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
             "build-tools;35.0.0" \
             "platform-tools" \
             "platforms;android-30" \
             "system-images;android-30;google_apis;arm64-v8a" \
-            "emulator"
+            "emulator" || true
 
       - name: Start Android Emulator
         uses: reactivecircus/android-emulator-runner@v2
@@ -56,22 +56,31 @@ jobs:
           target: ${{ matrix.target }}
           arch: ${{ matrix.arch }}
           profile: pixel_3a
-          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -wipe-data -qemu -m 2048"
+          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -wipe-data -no-vulkan -qemu -m 2048 -accel off"
           force-avd-creation: true
           emulator-boot-timeout: 1200
           disable-animations: true
           script: |
             adb wait-for-device
             sleep 30
-            adb shell input keyevent 82  # Разблокировка экрана
+            adb shell input keyevent 82
 
-
-      - name: Restart adb server
+      - name: Wait for Emulator Boot
         run: |
-          adb kill-server
-          adb start-server
           adb wait-for-device
-          sleep 30
+          for i in {1..30}; do
+            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
+            if [ "$boot_completed" == "1" ]; then
+              echo "Emulator booted successfully!"
+              break
+            fi
+            echo "Waiting for emulator to boot..."
+            sleep 10
+          done
+          if [ "$boot_completed" != "1" ]; then
+            echo "Emulator failed to boot!"
+            exit 1
+          fi
 
       - name: Run Instrumented Tests
         run: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.itog1.ExampleInstrumentedTest
